services:
  redis:
    image: redis:6
    ports:
      - 6379:6379
  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: success-development
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: ["postgres", "-c", "log_statement=all"]
volumes:
  pgdata:
